name: structure
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: '>=3.3.4 <4.0.0'

dependencies:
    cloud_firestore: ^5.0.1
    crypto: ^3.0.3
    cupertino_icons: ^1.0.8
    dotted_border: ^2.1.0
    email_validator: ^3.0.0
    firebase_auth: ^5.1.0
    firebase_core: ^3.1.0
    firebase_storage: ^12.0.1
    flutter:
        sdk: flutter
    flutter_screenutil: ^5.9.3
    flutter_spinkit : ^5.1.0
    go_router: ^14.2.0
    http: ^1.2.1
    image_picker: ^1.1.2
    intl: ^0.19.0
    kpostal: ^0.5.1
    path_provider: ^2.1.3
    provider: ^6.1.2
    syncfusion_flutter_sliders: ^26.1.38
    xml2json: ^6.2.3
    qr_flutter: ^4.1.0
    table_calendar: ^3.0.9
    qr_code_scanner: ^1.0.1
    flutter_svg: ^2.0.9
    flutter_dotenv: ^5.1.0
    camera: ^0.11.0+1
    flutter_spinkit: ^5.2.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^4.0.0

flutter:
    uses-material-design: true
    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/images/print.png
        - assets/images/eval_Color.png
        - assets/images/eval_Marbling.png
        - assets/images/eval_Overall.png
        - assets/images/eval_SurfaceMoisture.png
        - assets/images/eval_Texture.png
        - assets/images/deepaging_logo.svg
        - assets/images/deepplant_logo.svg
        - assets/images/arrow-b.png
        - assets/images/arrow-r.png
        - assets/images/chart.png
        - assets/images/qr.png
        - assets/images/pig.png
        - assets/images/person.png
        - assets/images/person.svg
        - assets/images/add_circle.png
        - assets/images/close.png
        - assets/images/data_register.png
        - assets/images/exit.png
        - assets/images/fresh_meat_eval.png
        - assets/images/picture_save.png
        - assets/images/trash.png
        - assets/images/warning.png
        - assets/images/meat_eval.png
        - assets/images/meat_info.png
        - assets/images/meat_image.png
        - assets/images/qr_scan.png
        - assets/images/meat_lab.png
        - assets/images/meat_tongue.png
        - assets/images/trash_image.png
        - assets/images/cam-shutter-in.png
        - assets/images/cam-shutter-out.png
        - assets/images/cam-shutter.png
        - .env

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware

    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    fonts:
        - family: Pretendard
          fonts:
              - asset: assets/fonts/Pretendard-Regular.otf
                weight: 400
              - asset: assets/fonts/Pretendard-Medium.otf
                weight: 500
              - asset: assets/fonts/Pretendard-SemiBold.otf
                weight: 600
              - asset: assets/fonts/Pretendard-Bold.otf
                weight: 700
